version: 2

updates:

  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: 'Asia/Colombo'
    open-pull-requests-limit: 10
    labels: ['deps', 'pip']
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'

  - package-ecosystem: github-actions
    directory: '/'
    schedule: { interval: weekly, day: monday, timezone: 'Asia/Colombo' }
    labels: ['deps', 'github-actions']
    commit-message: { prefix: 'chore(deps-ci)', include: 'scope' }

  - package-ecosystem: docker
    directory: '/'
    schedule: { interval: weekly, day: monday, timezone: 'Asia/Colombo' }
    labels: ['deps', 'docker']
    commit-message: { prefix: 'chore(deps-docker)', include: 'scope' }
